AllCops:
  NewCops: enable
  SuggestExtensions: false
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**
    - bin/bundle

Style/Documentation:
  Enabled: false